name: 'Container Action Recipe'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'mycustomaction'
  args:
    - ${{ inputs.who-to-greet }}
