name: Action CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Run my own container action
        id: my-action
        uses: ./
        with:
          who-to-greet: '@romulomf'
      - name: Output the answer
        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"