name: Action CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          image: mycustomaction
          containerfiles: ./Containerfile
      - name: Run my own container action
        uses: ./
        with:
          who-to-greet: '@romulomf'
